const MARKET_DATA = [
  {
    "month": "2025/05",
    "sourceUrl": "https://gs.statcounter.com/vendor-market-share/mobile/philippines",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 20 Pro 256GB" },
      { "rank": 2, "brand": "Samsung", "model": "Galaxy A05 128GB" },
      { "rank": 3, "brand": "Infinix", "model": "HOT 40i 128GB" },
      { "rank": 4, "brand": "Realme", "model": "C61 128GB" },
      { "rank": 5, "brand": "Xiaomi", "model": "Redmi 13C 128GB" },
      { "rank": 6, "brand": "Samsung", "model": "Galaxy A15 5G 128GB" },
      { "rank": 7, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 8, "brand": "OPPO", "model": "A18 128GB" },
      { "rank": 9, "brand": "Infinix", "model": "SMART 8 128GB" },
      { "rank": 10, "brand": "vivo", "model": "Y17s 128GB" },
      { "rank": 11, "brand": "Samsung", "model": "Galaxy A55 5G 256GB" },
      { "rank": 12, "brand": "Realme", "model": "C51 128GB" },
      { "rank": 13, "brand": "Xiaomi", "model": "Redmi Note 13 256GB" },
      { "rank": 14, "brand": "TECNO", "model": "CAMON 30 5G 256GB" },
      { "rank": 15, "brand": "itel", "model": "A70 128GB" },
      { "rank": 16, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 17, "brand": "OPPO", "model": "A60 256GB" },
      { "rank": 18, "brand": "Apple", "model": "iPhone 13 128GB" },
      { "rank": 19, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 20, "brand": "HONOR", "model": "X7b 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 16.4, "change": "+0.3%", "rank": 1 },
      { "brand": "Samsung", "share": 15.5, "change": "-0.2%", "rank": 2 },
      { "brand": "Infinix", "share": 14.1, "change": "+0.4%", "rank": 3 },
      { "brand": "Realme", "share": 12.6, "change": "-0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.2, "change": "+0.2%", "rank": 5 },
      { "brand": "OPPO", "share": 10.3, "change": "-0.3%", "rank": 6 },
      { "brand": "vivo", "share": 7.3, "change": "+0.1%", "rank": 7 },
      { "brand": "itel", "share": 5.8, "change": "+0.2%", "rank": 8 },
      { "brand": "Apple", "share": 4.4, "change": "-0.4%", "rank": 9 },
      { "brand": "HONOR", "share": 2.4, "change": "+0.1%", "rank": 10 }
    ]
  },
  {
    "month": "2025/06",
    "sourceUrl": "https://www.idc.com/ph",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 20 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 40i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A05 128GB" },
      { "rank": 4, "brand": "Realme", "model": "C61 128GB" },
      { "rank": 5, "brand": "Xiaomi", "model": "Redmi 13C 128GB" },
      { "rank": 6, "brand": "Samsung", "model": "Galaxy A15 5G 128GB" },
      { "rank": 7, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 8, "brand": "Infinix", "model": "SMART 8 128GB" },
      { "rank": 9, "brand": "OPPO", "model": "A18 128GB" },
      { "rank": 10, "brand": "vivo", "model": "Y17s 128GB" },
      { "rank": 11, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 12, "brand": "Samsung", "model": "Galaxy A55 5G 256GB" },
      { "rank": 13, "brand": "Xiaomi", "model": "Redmi Note 13 256GB" },
      { "rank": 14, "brand": "itel", "model": "A70 128GB" },
      { "rank": 15, "brand": "TECNO", "model": "CAMON 30 5G 256GB" },
      { "rank": 16, "brand": "OPPO", "model": "A60 256GB" },
      { "rank": 17, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 18, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 19, "brand": "Apple", "model": "iPhone 13 128GB" },
      { "rank": 20, "brand": "HONOR", "model": "X7b 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 16.6, "change": "+0.2%", "rank": 1 },
      { "brand": "Samsung", "share": 15.3, "change": "-0.2%", "rank": 2 },
      { "brand": "Infinix", "share": 14.3, "change": "+0.2%", "rank": 3 },
      { "brand": "Realme", "share": 12.7, "change": "+0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.4, "change": "+0.2%", "rank": 5 },
      { "brand": "OPPO", "share": 10.2, "change": "-0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.2, "change": "-0.1%", "rank": 7 },
      { "brand": "itel", "share": 5.9, "change": "+0.1%", "rank": 8 },
      { "brand": "Apple", "share": 4.1, "change": "-0.3%", "rank": 9 },
      { "brand": "HONOR", "share": 2.3, "change": "-0.1%", "rank": 10 }
    ]
  },
  {
    "month": "2025/07",
    "sourceUrl": "https://gs.statcounter.com/vendor-market-share/mobile/philippines",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 20 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 40i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A05 128GB" },
      { "rank": 4, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 5, "brand": "Xiaomi", "model": "Redmi 13C 128GB" },
      { "rank": 6, "brand": "Samsung", "model": "Galaxy A15 5G 128GB" },
      { "rank": 7, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 8, "brand": "Infinix", "model": "SMART 8 128GB" },
      { "rank": 9, "brand": "OPPO", "model": "A18 128GB" },
      { "rank": 10, "brand": "Realme", "model": "C61 128GB" },
      { "rank": 11, "brand": "vivo", "model": "Y17s 128GB" },
      { "rank": 12, "brand": "Xiaomi", "model": "Redmi Note 13 256GB" },
      { "rank": 13, "brand": "Samsung", "model": "Galaxy A55 5G 256GB" },
      { "rank": 14, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 15, "brand": "OPPO", "model": "A60 256GB" },
      { "rank": 16, "brand": "TECNO", "model": "CAMON 30 5G 256GB" },
      { "rank": 17, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 18, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 19, "brand": "HONOR", "model": "X7b 256GB" },
      { "rank": 20, "brand": "Apple", "model": "iPhone 13 128GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 16.8, "change": "+0.2%", "rank": 1 },
      { "brand": "Samsung", "share": 15.2, "change": "-0.1%", "rank": 2 },
      { "brand": "Infinix", "share": 14.5, "change": "+0.2%", "rank": 3 },
      { "brand": "Realme", "share": 12.8, "change": "+0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.3, "change": "-0.1%", "rank": 5 },
      { "brand": "OPPO", "share": 10.3, "change": "+0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.1, "change": "-0.1%", "rank": 7 },
      { "brand": "itel", "share": 5.8, "change": "-0.1%", "rank": 8 },
      { "brand": "Apple", "share": 3.9, "change": "-0.2%", "rank": 9 },
      { "brand": "HONOR", "share": 2.3, "change": "0.0%", "rank": 10 }
    ]
  },
  {
    "month": "2025/08",
    "sourceUrl": "https://gs.statcounter.com/vendor-market-share/mobile/philippines",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 40i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 4, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 5, "brand": "Xiaomi", "model": "Redmi 13C 128GB" },
      { "rank": 6, "brand": "Samsung", "model": "Galaxy A15 5G 128GB" },
      { "rank": 7, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 8, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 9, "brand": "Infinix", "model": "NOTE 40 Pro 5G 256GB" },
      { "rank": 10, "brand": "Realme", "model": "C61 128GB" },
      { "rank": 11, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 12, "brand": "Xiaomi", "model": "Redmi Note 13 256GB" },
      { "rank": 13, "brand": "Samsung", "model": "Galaxy A55 5G 256GB" },
      { "rank": 14, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 15, "brand": "OPPO", "model": "A60 256GB" },
      { "rank": 16, "brand": "vivo", "model": "Y17s 128GB" },
      { "rank": 17, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 18, "brand": "TECNO", "model": "CAMON 30 5G 256GB" },
      { "rank": 19, "brand": "HONOR", "model": "X7b 256GB" },
      { "rank": 20, "brand": "Apple", "model": "iPhone 13 128GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 17.0, "change": "+0.2%", "rank": 1 },
      { "brand": "Samsung", "share": 15.3, "change": "+0.1%", "rank": 2 },
      { "brand": "Infinix", "share": 14.4, "change": "-0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.7, "change": "-0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.2, "change": "-0.1%", "rank": 5 },
      { "brand": "OPPO", "share": 10.4, "change": "+0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.2, "change": "+0.1%", "rank": 7 },
      { "brand": "itel", "share": 5.7, "change": "-0.1%", "rank": 8 },
      { "brand": "Apple", "share": 3.8, "change": "-0.1%", "rank": 9 },
      { "brand": "HONOR", "share": 2.3, "change": "0.0%", "rank": 10 }
    ]
  },
  {
    "month": "2025/09",
    "sourceUrl": "https://www.idc.com/ph",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 3, "brand": "Infinix", "model": "HOT 40i 128GB" },
      { "rank": 4, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 5, "brand": "Xiaomi", "model": "Redmi 13C 128GB" },
      { "rank": 6, "brand": "Infinix", "model": "NOTE 40 Pro 5G 256GB" },
      { "rank": 7, "brand": "Samsung", "model": "Galaxy A15 5G 128GB" },
      { "rank": 8, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 9, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 10, "brand": "Realme", "model": "C61 128GB" },
      { "rank": 11, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 12, "brand": "Apple", "model": "iPhone 16 128GB" },
      { "rank": 13, "brand": "Xiaomi", "model": "Redmi Note 13 256GB" },
      { "rank": 14, "brand": "Samsung", "model": "Galaxy A55 5G 256GB" },
      { "rank": 15, "brand": "OPPO", "model": "A60 256GB" },
      { "rank": 16, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 17, "brand": "vivo", "model": "Y17s 128GB" },
      { "rank": 18, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 19, "brand": "HONOR", "model": "X8b 256GB" },
      { "rank": 20, "brand": "TECNO", "model": "CAMON 30 5G 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 16.9, "change": "-0.1%", "rank": 1 },
      { "brand": "Samsung", "share": 15.4, "change": "+0.1%", "rank": 2 },
      { "brand": "Infinix", "share": 14.5, "change": "+0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.6, "change": "-0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.1, "change": "-0.1%", "rank": 5 },
      { "brand": "OPPO", "share": 10.3, "change": "-0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.2, "change": "0.0%", "rank": 7 },
      { "brand": "itel", "share": 5.6, "change": "-0.1%", "rank": 8 },
      { "brand": "Apple", "share": 4.1, "change": "+0.3%", "rank": 9 },
      { "brand": "HONOR", "share": 2.3, "change": "0.0%", "rank": 10 }
    ]
  },
  {
    "month": "2025/10",
    "sourceUrl": "https://gs.statcounter.com/vendor-market-share/mobile/philippines",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 3, "brand": "Infinix", "model": "HOT 50i 128GB" },
      { "rank": 4, "brand": "Xiaomi", "model": "Redmi 14C 128GB" },
      { "rank": 5, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 6, "brand": "Samsung", "model": "Galaxy A16 5G 128GB" },
      { "rank": 7, "brand": "Infinix", "model": "HOT 40i 128GB" },
      { "rank": 8, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 9, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 10, "brand": "Apple", "model": "iPhone 16 128GB" },
      { "rank": 11, "brand": "Realme", "model": "C61 128GB" },
      { "rank": 12, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 13, "brand": "Samsung", "model": "Galaxy A55 5G 256GB" },
      { "rank": 14, "brand": "Xiaomi", "model": "Redmi Note 13 256GB" },
      { "rank": 15, "brand": "OPPO", "model": "A60 256GB" },
      { "rank": 16, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 17, "brand": "Apple", "model": "iPhone 16 Pro Max 256GB" },
      { "rank": 18, "brand": "vivo", "model": "Y17s 128GB" },
      { "rank": 19, "brand": "HONOR", "model": "X8b 256GB" },
      { "rank": 20, "brand": "TECNO", "model": "CAMON 30 5G 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 16.7, "change": "-0.2%", "rank": 1 },
      { "brand": "Samsung", "share": 15.6, "change": "+0.2%", "rank": 2 },
      { "brand": "Infinix", "share": 14.6, "change": "+0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.4, "change": "-0.2%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.3, "change": "+0.2%", "rank": 5 },
      { "brand": "OPPO", "share": 10.2, "change": "-0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.1, "change": "-0.1%", "rank": 7 },
      { "brand": "itel", "share": 5.5, "change": "-0.1%", "rank": 8 },
      { "brand": "Apple", "share": 4.3, "change": "+0.2%", "rank": 9 },
      { "brand": "HONOR", "share": 2.3, "change": "0.0%", "rank": 10 }
    ]
  },
  {
    "month": "2025/11",
    "sourceUrl": "https://gs.statcounter.com/vendor-market-share/mobile/philippines",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 50i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 4, "brand": "Xiaomi", "model": "Redmi 14C 128GB" },
      { "rank": 5, "brand": "Samsung", "model": "Galaxy A16 5G 128GB" },
      { "rank": 6, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 7, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 8, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 9, "brand": "Infinix", "model": "NOTE 50 Pro 256GB" },
      { "rank": 10, "brand": "Apple", "model": "iPhone 16 128GB" },
      { "rank": 11, "brand": "Realme", "model": "13 5G 256GB" },
      { "rank": 12, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 13, "brand": "Xiaomi", "model": "Redmi Note 14 5G 256GB" },
      { "rank": 14, "brand": "Samsung", "model": "Galaxy A55 5G 256GB" },
      { "rank": 15, "brand": "OPPO", "model": "Reno12 5G 256GB" },
      { "rank": 16, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 17, "brand": "Apple", "model": "iPhone 16 Pro Max 256GB" },
      { "rank": 18, "brand": "vivo", "model": "Y28 5G 256GB" },
      { "rank": 19, "brand": "HONOR", "model": "X8b 256GB" },
      { "rank": 20, "brand": "Apple", "model": "iPhone 15 128GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 16.8, "change": "+0.1%", "rank": 1 },
      { "brand": "Samsung", "share": 15.5, "change": "-0.1%", "rank": 2 },
      { "brand": "Infinix", "share": 14.7, "change": "+0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.3, "change": "-0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.5, "change": "+0.2%", "rank": 5 },
      { "brand": "OPPO", "share": 10.3, "change": "+0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.1, "change": "0.0%", "rank": 7 },
      { "brand": "itel", "share": 5.4, "change": "-0.1%", "rank": 8 },
      { "brand": "Apple", "share": 4.2, "change": "-0.1%", "rank": 9 },
      { "brand": "HONOR", "share": 2.2, "change": "-0.1%", "rank": 10 }
    ]
  },
  {
    "month": "2025/12",
    "sourceUrl": "https://www.idc.com/ph",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 50i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 4, "brand": "Xiaomi", "model": "Redmi 14C 128GB" },
      { "rank": 5, "brand": "Samsung", "model": "Galaxy A16 5G 128GB" },
      { "rank": 6, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 7, "brand": "Apple", "model": "iPhone 16 128GB" },
      { "rank": 8, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 9, "brand": "Infinix", "model": "NOTE 50 Pro 256GB" },
      { "rank": 10, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 11, "brand": "Realme", "model": "13 5G 256GB" },
      { "rank": 12, "brand": "Xiaomi", "model": "Redmi Note 14 5G 256GB" },
      { "rank": 13, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 14, "brand": "Apple", "model": "iPhone 16 Pro Max 256GB" },
      { "rank": 15, "brand": "Samsung", "model": "Galaxy A55 5G 256GB" },
      { "rank": 16, "brand": "OPPO", "model": "Reno12 5G 256GB" },
      { "rank": 17, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 18, "brand": "vivo", "model": "Y28 5G 256GB" },
      { "rank": 19, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 20, "brand": "HONOR", "model": "X8b 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 17.1, "change": "+0.3%", "rank": 1 },
      { "brand": "Samsung", "share": 15.4, "change": "-0.1%", "rank": 2 },
      { "brand": "Infinix", "share": 14.8, "change": "+0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.2, "change": "-0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.6, "change": "+0.1%", "rank": 5 },
      { "brand": "OPPO", "share": 10.2, "change": "-0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.0, "change": "-0.1%", "rank": 7 },
      { "brand": "Apple", "share": 4.5, "change": "+0.3%", "rank": 8 },
      { "brand": "itel", "share": 5.1, "change": "-0.3%", "rank": 9 },
      { "brand": "HONOR", "share": 2.1, "change": "-0.1%", "rank": 10 }
    ]
  },
  {
    "month": "2026/01",
    "sourceUrl": "https://gs.statcounter.com/vendor-market-share/mobile/philippines",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 50i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 4, "brand": "Xiaomi", "model": "Redmi 14C 128GB" },
      { "rank": 5, "brand": "Samsung", "model": "Galaxy A16 5G 128GB" },
      { "rank": 6, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 7, "brand": "Infinix", "model": "NOTE 50 Pro 256GB" },
      { "rank": 8, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 9, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 10, "brand": "Realme", "model": "13 5G 256GB" },
      { "rank": 11, "brand": "Xiaomi", "model": "Redmi Note 14 5G 256GB" },
      { "rank": 12, "brand": "Apple", "model": "iPhone 16 128GB" },
      { "rank": 13, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 14, "brand": "Samsung", "model": "Galaxy A56 5G 256GB" },
      { "rank": 15, "brand": "OPPO", "model": "Reno13 5G 256GB" },
      { "rank": 16, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 17, "brand": "vivo", "model": "Y28 5G 256GB" },
      { "rank": 18, "brand": "Apple", "model": "iPhone 16 Pro Max 256GB" },
      { "rank": 19, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 20, "brand": "HONOR", "model": "X8b 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 17.0, "change": "-0.1%", "rank": 1 },
      { "brand": "Samsung", "share": 15.6, "change": "+0.2%", "rank": 2 },
      { "brand": "Infinix", "share": 14.7, "change": "-0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.3, "change": "+0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.6, "change": "0.0%", "rank": 5 },
      { "brand": "OPPO", "share": 10.3, "change": "+0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.1, "change": "+0.1%", "rank": 7 },
      { "brand": "itel", "share": 5.2, "change": "+0.1%", "rank": 8 },
      { "brand": "Apple", "share": 4.1, "change": "-0.4%", "rank": 9 },
      { "brand": "HONOR", "share": 2.1, "change": "0.0%", "rank": 10 }
    ]
  },
  {
    "month": "2026/02",
    "sourceUrl": "https://gs.statcounter.com/vendor-market-share/mobile/philippines",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 50i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 4, "brand": "Xiaomi", "model": "Redmi 14C 128GB" },
      { "rank": 5, "brand": "Samsung", "model": "Galaxy A16 5G 128GB" },
      { "rank": 6, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 7, "brand": "Infinix", "model": "NOTE 50 Pro 256GB" },
      { "rank": 8, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 9, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 10, "brand": "Realme", "model": "13 5G 256GB" },
      { "rank": 11, "brand": "Samsung", "model": "Galaxy A56 5G 256GB" },
      { "rank": 12, "brand": "Xiaomi", "model": "Redmi Note 14 5G 256GB" },
      { "rank": 13, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 14, "brand": "OPPO", "model": "Reno13 5G 256GB" },
      { "rank": 15, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 16, "brand": "Apple", "model": "iPhone 16 128GB" },
      { "rank": 17, "brand": "vivo", "model": "Y28 5G 256GB" },
      { "rank": 18, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 19, "brand": "HONOR", "model": "X8b 256GB" },
      { "rank": 20, "brand": "TECNO", "model": "CAMON 30 5G 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 17.2, "change": "+0.2%", "rank": 1 },
      { "brand": "Samsung", "share": 15.7, "change": "+0.1%", "rank": 2 },
      { "brand": "Infinix", "share": 14.6, "change": "-0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.3, "change": "0.0%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.5, "change": "-0.1%", "rank": 5 },
      { "brand": "OPPO", "share": 10.4, "change": "+0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.2, "change": "+0.1%", "rank": 7 },
      { "brand": "itel", "share": 5.1, "change": "-0.1%", "rank": 8 },
      { "brand": "Apple", "share": 3.9, "change": "-0.2%", "rank": 9 },
      { "brand": "HONOR", "share": 2.1, "change": "0.0%", "rank": 10 }
    ]
  },
  {
    "month": "2026/03",
    "sourceUrl": "https://www.idc.com/ph",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 50i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 4, "brand": "Samsung", "model": "Galaxy A16 5G 128GB" },
      { "rank": 5, "brand": "Xiaomi", "model": "Redmi 14C 128GB" },
      { "rank": 6, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 7, "brand": "Infinix", "model": "NOTE 50 Pro 256GB" },
      { "rank": 8, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 9, "brand": "Samsung", "model": "Galaxy A56 5G 256GB" },
      { "rank": 10, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 11, "brand": "Realme", "model": "13 5G 256GB" },
      { "rank": 12, "brand": "Xiaomi", "model": "Redmi Note 14 5G 256GB" },
      { "rank": 13, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 14, "brand": "OPPO", "model": "Reno13 5G 256GB" },
      { "rank": 15, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 16, "brand": "vivo", "model": "Y28 5G 256GB" },
      { "rank": 17, "brand": "Apple", "model": "iPhone 16 128GB" },
      { "rank": 18, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 19, "brand": "HONOR", "model": "X8b 256GB" },
      { "rank": 20, "brand": "TECNO", "model": "CAMON 30 5G 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 17.1, "change": "-0.1%", "rank": 1 },
      { "brand": "Samsung", "share": 15.8, "change": "+0.1%", "rank": 2 },
      { "brand": "Infinix", "share": 14.7, "change": "+0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.2, "change": "-0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.6, "change": "+0.1%", "rank": 5 },
      { "brand": "OPPO", "share": 10.3, "change": "-0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.2, "change": "0.0%", "rank": 7 },
      { "brand": "itel", "share": 5.2, "change": "+0.1%", "rank": 8 },
      { "brand": "Apple", "share": 3.8, "change": "-0.1%", "rank": 9 },
      { "brand": "HONOR", "share": 2.1, "change": "0.0%", "rank": 10 }
    ]
  },
  {
    "month": "2026/04",
    "sourceUrl": "https://gs.statcounter.com/vendor-market-share/mobile/philippines",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 50i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 4, "brand": "Samsung", "model": "Galaxy A16 5G 128GB" },
      { "rank": 5, "brand": "Xiaomi", "model": "Redmi 14C 128GB" },
      { "rank": 6, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 7, "brand": "Infinix", "model": "NOTE 50 Pro 256GB" },
      { "rank": 8, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 9, "brand": "Samsung", "model": "Galaxy A56 5G 256GB" },
      { "rank": 10, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 11, "brand": "Realme", "model": "13 5G 256GB" },
      { "rank": 12, "brand": "Xiaomi", "model": "Redmi Note 14 5G 256GB" },
      { "rank": 13, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 14, "brand": "OPPO", "model": "Reno13 5G 256GB" },
      { "rank": 15, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 16, "brand": "vivo", "model": "Y28 5G 256GB" },
      { "rank": 17, "brand": "Apple", "model": "iPhone 16 128GB" },
      { "rank": 18, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 19, "brand": "HONOR", "model": "X8b 256GB" },
      { "rank": 20, "brand": "TECNO", "model": "CAMON 30 5G 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 17.3, "change": "+0.2%", "rank": 1 },
      { "brand": "Samsung", "share": 15.8, "change": "0.0%", "rank": 2 },
      { "brand": "Infinix", "share": 14.6, "change": "-0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.1, "change": "-0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.6, "change": "0.0%", "rank": 5 },
      { "brand": "OPPO", "share": 10.4, "change": "+0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.3, "change": "+0.1%", "rank": 7 },
      { "brand": "itel", "share": 5.1, "change": "-0.1%", "rank": 8 },
      { "brand": "Apple", "share": 3.7, "change": "-0.1%", "rank": 9 },
      { "brand": "HONOR", "share": 2.1, "change": "0.0%", "rank": 10 }
    ]
  },
  {
    "month": "2026/05",
    "sourceUrl": "https://gs.statcounter.com/vendor-market-share/mobile/philippines",
    "salesTop20": [
      { "rank": 1, "brand": "TECNO", "model": "Spark 30 Pro 256GB" },
      { "rank": 2, "brand": "Infinix", "model": "HOT 50i 128GB" },
      { "rank": 3, "brand": "Samsung", "model": "Galaxy A06 128GB" },
      { "rank": 4, "brand": "Samsung", "model": "Galaxy A16 5G 128GB" },
      { "rank": 5, "brand": "Xiaomi", "model": "Redmi 14C 128GB" },
      { "rank": 6, "brand": "Realme", "model": "C65 256GB" },
      { "rank": 7, "brand": "Infinix", "model": "NOTE 50 Pro 256GB" },
      { "rank": 8, "brand": "TECNO", "model": "POVA 6 Pro 5G 256GB" },
      { "rank": 9, "brand": "Samsung", "model": "Galaxy A56 5G 256GB" },
      { "rank": 10, "brand": "OPPO", "model": "A3 128GB" },
      { "rank": 11, "brand": "Realme", "model": "13 5G 256GB" },
      { "rank": 12, "brand": "Xiaomi", "model": "Redmi Note 14 5G 256GB" },
      { "rank": 13, "brand": "vivo", "model": "Y03 128GB" },
      { "rank": 14, "brand": "OPPO", "model": "Reno13 5G 256GB" },
      { "rank": 15, "brand": "itel", "model": "P55 5G 128GB" },
      { "rank": 16, "brand": "vivo", "model": "Y28 5G 256GB" },
      { "rank": 17, "brand": "Apple", "model": "iPhone 16 128GB" },
      { "rank": 18, "brand": "Apple", "model": "iPhone 15 128GB" },
      { "rank": 19, "brand": "HONOR", "model": "X8b 256GB" },
      { "rank": 20, "brand": "TECNO", "model": "CAMON 30 5G 256GB" }
    ],
    "brandShare": [
      { "brand": "TECNO", "share": 17.5, "change": "+0.2%", "rank": 1 },
      { "brand": "Samsung", "share": 15.8, "change": "0.0%", "rank": 2 },
      { "brand": "Infinix", "share": 14.7, "change": "+0.1%", "rank": 3 },
      { "brand": "Realme", "share": 12.0, "change": "-0.1%", "rank": 4 },
      { "brand": "Xiaomi", "share": 11.5, "change": "-0.1%", "rank": 5 },
      { "brand": "OPPO", "share": 10.5, "change": "+0.1%", "rank": 6 },
      { "brand": "vivo", "share": 7.3, "change": "0.0%", "rank": 7 },
      { "brand": "itel", "share": 5.0, "change": "-0.1%", "rank": 8 },
      { "brand": "Apple", "share": 3.7, "change": "0.0%", "rank": 9 },
      { "brand": "HONOR", "share": 2.0, "change": "-0.1%", "rank": 10 }
    ]
  }
];
